- name: Ensure ~/.ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.shh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Install Public SSH key
  authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', 'roles/users/files/id_ed25519.pub') }}"

- name: Install private SSH key from Vault
  copy:
    src: vault/id_ed25519
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0600'
