- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present
    update_cache: true

- name: Set system hostname
  hostname:
    name: "{{ hostname }}"

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
